git:
  submodules: false

branches:
  only:
  - master
  
env:
  global:
    - PRODUCT=3d
    - SRC_DIR=public
    - DEST_DIR=/var/www/docs.aspose.com/html

before_install:
- openssl aes-256-cbc -K $encrypted_dfdcfd5172af_key -iv $encrypted_dfdcfd5172af_iv
  -in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host $HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key

install:
- curl -LO https://github.com/gohugoio/hugo/releases/download/v0.67.1/hugo_extended_0.67.1_Linux-64bit.deb
- sudo dpkg -i hugo_extended_0.67.1_Linux-64bit.deb

script:
- travis_wait 60 hugo --minify --config config.toml

after_success:
- travis_wait 60 scp -i ./deploy_key -r $SRC_DIR/* $USER@$HOST:$DEST_DIR/$PRODUCT




